# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='order.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0border.proto\"\x1f\n\x0cOrderRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"O\n\rOrderResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncustomerId\x18\x02 \x01(\t\x12\x1e\n\norderLines\x18\x03 \x03(\x0b\x32\n.OrderLine\"Q\n\tOrderLine\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07orderId\x18\x02 \x01(\t\x12\x11\n\tproductId\x18\x03 \x01(\t\x12\x14\n\x0cproductPrice\x18\x04 \x01(\x01\x32\x36\n\x05Order\x12-\n\x0cGetOrderByID\x12\r.OrderRequest\x1a\x0e.OrderResponseb\x06proto3')
)




_ORDERREQUEST = _descriptor.Descriptor(
  name='OrderRequest',
  full_name='OrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderId', full_name='OrderRequest.orderId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=46,
)


_ORDERRESPONSE = _descriptor.Descriptor(
  name='OrderResponse',
  full_name='OrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='OrderResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customerId', full_name='OrderResponse.customerId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderLines', full_name='OrderResponse.orderLines', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=127,
)


_ORDERLINE = _descriptor.Descriptor(
  name='OrderLine',
  full_name='OrderLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='OrderLine.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderId', full_name='OrderLine.orderId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productId', full_name='OrderLine.productId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productPrice', full_name='OrderLine.productPrice', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=210,
)

_ORDERRESPONSE.fields_by_name['orderLines'].message_type = _ORDERLINE
DESCRIPTOR.message_types_by_name['OrderRequest'] = _ORDERREQUEST
DESCRIPTOR.message_types_by_name['OrderResponse'] = _ORDERRESPONSE
DESCRIPTOR.message_types_by_name['OrderLine'] = _ORDERLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderRequest = _reflection.GeneratedProtocolMessageType('OrderRequest', (_message.Message,), dict(
  DESCRIPTOR = _ORDERREQUEST,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderRequest)
  ))
_sym_db.RegisterMessage(OrderRequest)

OrderResponse = _reflection.GeneratedProtocolMessageType('OrderResponse', (_message.Message,), dict(
  DESCRIPTOR = _ORDERRESPONSE,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderResponse)
  ))
_sym_db.RegisterMessage(OrderResponse)

OrderLine = _reflection.GeneratedProtocolMessageType('OrderLine', (_message.Message,), dict(
  DESCRIPTOR = _ORDERLINE,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderLine)
  ))
_sym_db.RegisterMessage(OrderLine)



_ORDER = _descriptor.ServiceDescriptor(
  name='Order',
  full_name='Order',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=212,
  serialized_end=266,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOrderByID',
    full_name='Order.GetOrderByID',
    index=0,
    containing_service=None,
    input_type=_ORDERREQUEST,
    output_type=_ORDERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDER)

DESCRIPTOR.services_by_name['Order'] = _ORDER

# @@protoc_insertion_point(module_scope)
