AMQP_URI: ${QUEUE_HOST}
WEB_SERVER_ADDRESS: ${WEB_SERVER_ADDRESS}
max_workers: 10
parent_calls_tracked: 10

DB_URIS:
    "news_service:Base": ${DATABASE_URL}

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
    root:
        level: DEBUG
        handlers: [console]
