version: '3'

services:

  # ----------------------------------------
  # ----------------------------------------
  # RabbitMQ
  # ----------------------------------------
  # ----------------------------------------

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  # ----------------------------------------
  # ----------------------------------------
  # News Database
  # ----------------------------------------
  # ----------------------------------------

  news_service_db:
    build: ./news_service_db
    ports:
      - 5432:5432  # expose ports - HOST:CONTAINER
    volumes:
      - 'news-postgres-data:/var/lib/postgresql/data/'
    healthcheck:
      test: exit 0
    restart: always

  # ----------------------------------------
  # ----------------------------------------
  # News Microservice Flask
  # ----------------------------------------
  # ----------------------------------------

  news_flask:
    image: news_flask
    build: ./news_service_flask
    environment:
      - APP_ENV=development
      - APP_PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@news_service_db:5432/news_db?sslmode=disable
    depends_on:
      - news_service_db
    links:
      - news_service_db
    ports:
      - 5000:5000
    restart: always

  # ----------------------------------------
  # ----------------------------------------
  # News Microservice Nameko
  # ----------------------------------------
  # ----------------------------------------

  news_nameko:
    image: news_nameko
    build: ./news_service_nameko
    environment:
      - QUEUE_HOST=amqp://guest:guest@rabbitmq
      - WEB_SERVER_ADDRESS=0.0.0.0:5001
      - DATABASE_URL=postgresql://postgres:postgres@news_service_db:5432/news_db?sslmode=disable
    depends_on:
      - news_service_db
      - rabbitmq
    links:
      - news_service_db
      - rabbitmq
    ports:
      - 5001:5001
    restart: always

volumes:
  news-postgres-data:
