POST http://localhost:5000/news/
content-type: application/json

{
    "author": "Vinicius Pacheco",
    "title": "Python Microservices Cookbook",
    "content": "This book will be released in June",
    "is_active": true,
    "tags": ["books", "microservices", "Python"]
}

###

PUT http://localhost:5000/news/1
content-type: application/json

{
    "author": "Vinicius Pacheco",
    "title": "Python Microservices Cookbook",
    "content": "This book will be released in June",
    "is_active": true,
    "tags": ["books", "microservices", "Python", "Flask"]
}

###

GET http://localhost:5000/news/1

###

GET http://localhost:5000/news/

###

DELETE http://localhost:5000/news/1
