"""baseline

Revision ID: 922e12c4dbbd
Revises: 
Create Date: 2019-04-14 04:39:41.887222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '922e12c4dbbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=True),
    sa.Column('author', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_index('index_by_id', 'news', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_by_id', table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
