AMQP_URI: ${QUEUE_HOST}
WEB_SERVER_ADDRESS: ${WEB_SERVER_ADDRESS}
max_workers: 10
parent_calls_tracked: 10

DB_URIS:
    "orders_domain:Base": ${DATABASE_URL}

GRPC_BIND_PORT: ${GRPC_BIND_PORT:50051}

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
    root:
        level: DEBUG
        handlers: [console]
