POST http://localhost:5000/create_news
content-type: application/json

{
    "author": "Vinicius Pacheco",
    "title": "Python Microservices Cookbook",
    "content": "This book will be released in June",
    "is_active": true,
    "tags": ["books", "microservices", "Python"]
}

###

GET http://localhost:5000/news/1

###

GET http://localhost:5000/news/list/page/1/limit/10

###

GET http://localhost:5000/news/1a34f088-535e-11e9-a725-0242ac120005
