"""baseline

Revision ID: 50bc9e8c4b6f
Revises: 
Create Date: 2019-05-02 02:25:19.744017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bc9e8c4b6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=250), nullable=False),
    sa.Column('customer_id', sa.String(length=250), nullable=True),
    sa.Column('order_id', sa.String(length=250), nullable=True),
    sa.Column('value_processed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
